### ISSUE TITLE
Hello, I wonder how to visualize the GradCAM of the model.

### ISSUE THREAD

**Issue by Mr-Bigworth** [uvavision/AMC-grounding#1]
As shown in figure 2 of the paper, the GradCAM can be visualized on the image. And I wonder how to compute the GradCAM of the model. Thanks!

**Comment by ziyanyang** [comment]
Hi, I just uploaded the demo file here (https://github.com/uvavision/AMC-grounding/blob/main/demo_amc.ipynb). Let me know if you have questions.

**Comment by Mr-Bigworth** [comment]
> Hi, I just uploaded the demo file here (https://github.com/uvavision/AMC-grounding/blob/main/demo_amc.ipynb). Let me know if you have questions.

Thanks!!
