### ISSUE TITLE
An issue about the paper

### ISSUE THREAD

**Issue by xwhzz** [uvavision/AMC-grounding#2]
In sec3.2, I wonder whether eq(5) and explanation about it is correct. I don't find this corresponding implementation in your code.
![IMG_20231220_202241](https://github.com/uvavision/AMC-grounding/assets/132904306/bb3f0eb5-f5eb-43bb-ae58-0943b7427238)

**Comment by ziyanyang** [comment]
> In sec3.2, I wonder whether eq(5) and explanation about it is correct. I don't find this corresponding implementation in your code. ![IMG_20231220_202241](https://private-user-images.githubusercontent.com/132904306/291892190-bb3f0eb5-f5eb-43bb-ae58-0943b7427238.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4Njg2MzYsIm5iZiI6MTcwNTg2ODMzNiwicGF0aCI6Ii8xMzI5MDQzMDYvMjkxODkyMTkwLWJiM2YwZWI1LWY1ZWItNDNiYi1hZTU4LTA5NDNiNzQyNzIzOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQyMDE4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTAyYTkzNDYwZmEwYzExOGZlNTkyMTdhNTRjOTMxYjA0YWVlZmVjM2Y4YjdmNjY3ZDhmZjlmZjI3MjkzMWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKl8vVpz5hA5ygXqkEWzile9_nVaL9eC02Vvuc2E-F0)

It is implemented in the [model](https://github.com/uvavision/AMC-grounding/blob/main/models/model_pretrain.py#L198) file.
